import { BeneficiaryClass, BeneficiaryStats } from "./types";

export const MOCK_CLASSES: BeneficiaryClass[] = [
  {
    id: "cls-001",
    schoolName: "SMPN 03 Jakarta",
    className: "Kelas 7A",
    teacherName: "Ibu Ratna",
    totalRegistered: 32,
    presentToday: 30,
    sickCount: 2,
    absentCount: 0,
    targetPortions: 30,
    distributionStatus: "sedang_dikirim",
    lastSyncTime: "07:00 WIB",
  },
  {
    id: "cls-002",
    schoolName: "SMPN 03 Jakarta",
    className: "Kelas 7B",
    teacherName: "Bpk. Budi",
    totalRegistered: 30,
    presentToday: 30,
    sickCount: 0,
    absentCount: 0,
    targetPortions: 30,
    distributionStatus: "terkirim",
    lastSyncTime: "07:00 WIB",
  },
  {
    id: "cls-003",
    schoolName: "SDN 02 Palmerah",
    className: "Kelas 1A",
    teacherName: "Ibu Siti",
    totalRegistered: 28,
    presentToday: null,
    sickCount: 0,
    absentCount: 0,
    targetPortions: null,
    distributionStatus: "belum_sync",
  },
  {
    id: "cls-004",
    schoolName: "SDN 02 Palmerah",
    className: "Kelas 2B",
    teacherName: "Bpk. Agus",
    totalRegistered: 30,
    presentToday: 28,
    sickCount: 1,
    absentCount: 1,
    targetPortions: 28,
    distributionStatus: "terkirim",
    lastSyncTime: "07:05 WIB",
  },
  {
    id: "cls-005",
    schoolName: "SMPN 03 Jakarta",
    className: "Kelas 8A",
    teacherName: "Ibu Dewi",
    totalRegistered: 35,
    presentToday: 33,
    sickCount: 1,
    absentCount: 1,
    targetPortions: 33,
    distributionStatus: "menunggu",
    lastSyncTime: "07:02 WIB",
  },
];

export const MOCK_STATS: BeneficiaryStats = {
  totalRegistered: 1280,
  totalSchools: 3,
  presentToday: 1250,
  absentToday: 30,
  syncedClasses: 4,
  totalClasses: 5,
};
