export interface Region {
  name: string;
  regencies: Regency[];
}

export interface Regency {
  name: string;
  districts: string[];
}

export const REGIONS: Region[] = [
  {
    name: "Jawa Barat",
    regencies: [
      {
        name: "Kab. Purwakarta",
        districts: [
          "Purwakarta",
          "Wanayasa",
          "Jatiluhur",
          "Plered",
          "Sukatani",
          "Pasawahan",
          "Kampung Dalem",
          "Cibatu",
          "Bungursari",
          "Tegal Waru",
          "Sukamukti",
          "Maniis",
        ],
      },
      {
        name: "Kab. Subang",
        districts: [
          "Subang",
          "Pagenjahan",
          "Purwadadi",
          "Kalijati",
          "Tanjungsiang",
          "Compreng",
          "Binong",
          "Ciasem",
          "Pusakanagara",
          "Purwakarta",
          "Legonkulon",
          "Blanakan",
        ],
      },
      {
        name: "Kab. Karawang",
        districts: [
          "Karawang",
          "Klari",
          "Rengasdengklok",
          "Kutawaluya",
          "Batujaya",
          "Tirtajaya",
          "Cibuaya",
          "Cikampek",
          "Purwasari",
          "Tegalwaru",
          "Rawamerta",
          "Majalaya",
        ],
      },
      {
        name: "Kab. Bogor",
        districts: [
          "Bogor",
          "Bogor Barat",
          "Bogor Tengah",
          "Bogor Timur",
          "Bogor Utara",
          "Tanah Sareal",
          "Cibinong",
          "Citeureup",
          "Sukaraja",
          "Babakan Madang",
          "Sentul",
          "Caringin",
        ],
      },
      {
        name: "Kab. Bandung",
        districts: [
          "Soreang",
          "Kutawaringin",
          "Pangalengan",
          "Cimaung",
          "Malakasari",
          "Baleendah",
          "Arjasari",
          "Ciparay",
          "Bale Bandung",
          "Margaasih",
          "Cimenyan",
        ],
      },
      {
        name: "Kota Bandung",
        districts: [
          "Bandung Wetan",
          "Bandung Kidul",
          "Bandung Kulon",
          "Bandung Tengah",
          "Bandung Barat",
          "Bandung Timur",
          "Coblong",
          "Cibeunying",
          "Sukasari",
          "Cidadap",
        ],
      },
      {
        name: "Kota Bekasi",
        districts: [
          "Bekasi Timur",
          "Bekasi Barat",
          "Bekasi Utara",
          "Bekasi Selatan",
          "Bekasi Kota",
          "Jatisampurna",
          "Jatiasih",
          "Pondok Gede",
          "Pondok Melati",
          "Mustika Jaya",
        ],
      },
      {
        name: "Kab. Cirebon",
        districts: [
          "Sumber",
          "Baran",
          "Ciledug",
          "Lemahabang",
          "Susukan",
          "Arjawinangun",
          "Pangenan",
          "Mundu",
          "Beber",
          "Talun",
          "Dukupuntang",
          "Palimanan",
          "Plumbon",
          "Weru",
          "Kedawung",
          "Ketanggungan",
          "Gempol",
          "Plered",
          "Tengah Tani",
          "Pajagan",
          "Klangenan",
          "Ciledug Lor",
        ],
      },
      {
        name: "Kota Cirebon",
        districts: [
          "Kejaksan",
          "Kesambi",
          "Harjamukti",
          "Lemahwungkuk",
          "Pekalipan",
        ],
      },
    ],
  },
  {
    name: "DKI Jakarta",
    regencies: [
      {
        name: "Jakarta Pusat",
        districts: [
          "Menteng",
          "Senen",
          "Tanah Abang",
          "Menteng Dalam",
          "Kramat",
          "Paseban",
          "Bungur Besar",
          "Kemayoran",
          "Sawah Besar",
        ],
      },
      {
        name: "Jakarta Utara",
        districts: [
          "Penjaringan",
          "Tanjung Priok",
          "Koja",
          "Kelapa Gading",
          "Pademangan",
          "Cilincing",
        ],
      },
      {
        name: "Jakarta Selatan",
        districts: [
          "Kebayoran Baru",
          "Kebayoran Lama",
          "Pesanggrahan",
          "Cilandak",
          "Pasar Minggu",
          "Jagakarsa",
          "Tebet",
          "Setiaabadi",
        ],
      },
      {
        name: "Jakarta Barat",
        districts: [
          "Tambora",
          "Taman Sari",
          "Menteng Dalam",
          "Grogol",
          "Palmerah",
          "Kembangan",
          "Kebon Jeruk",
          "Cengkareng",
          "Kalideres",
        ],
      },
      {
        name: "Jakarta Timur",
        districts: [
          "Matraman",
          "Pulo Gadung",
          "Jatinegara",
          "Cakung",
          "Pisangan Baru",
          "Ciracas",
          "Kramatjati",
          "Duren Sawit",
          "Makasar",
        ],
      },
    ],
  },
  {
    name: "Jawa Tengah",
    regencies: [
      {
        name: "Kab. Semarang",
        districts: [
          "Ungaran Barat",
          "Ungaran Timur",
          "Bergas",
          "Pringapus",
          "Banding",
          "Susukan",
          "Bringin",
          "Getasan",
        ],
      },
      {
        name: "Kota Semarang",
        districts: [
          "Semarang Tengah",
          "Semarang Utara",
          "Semarang Timur",
          "Semarang Selatan",
          "Semarang Barat",
          "Genuk",
          "Tugu",
          "Mijen",
        ],
      },
      {
        name: "Kab. Solo",
        districts: [
          "Colomadu",
          "Gondangrejo",
          "Sawit",
          "Banyudono",
          "Mojosongo",
          "Teras",
          "Fajar",
        ],
      },
      {
        name: "Kota Surakarta",
        districts: [
          "Banjarsari",
          "Jebres",
          "Kota Barat",
          "Laweyan",
          "Serengan",
        ],
      },
    ],
  },
  {
    name: "Jawa Timur",
    regencies: [
      {
        name: "Kab. Sidoarjo",
        districts: [
          "Sidoarjo",
          "Taman",
          "Tulangan",
          "Wonoayu",
          "Krembung",
          "Porong",
          "Tanggulangin",
          "Candi",
        ],
      },
      {
        name: "Kota Surabaya",
        districts: [
          "Gubeng",
          "Wonokromo",
          "Tegalsari",
          "Kayoon",
          "Kenjeran",
          "Genteng",
          "Tandes",
          "Benowo",
        ],
      },
      {
        name: "Kab. Malang",
        districts: [
          "Kepanjen",
          "Ngajum",
          "Wonosari",
          "Pagak",
          "Bantur",
          "Sumbermanjing",
          "Dampit",
          "Ampelgading",
        ],
      },
    ],
  },
  {
    name: "Banten",
    regencies: [
      {
        name: "Kab. Tangerang",
        districts: [
          "Tigaraksa",
          "Jatiuwung",
          "Cikupa",
          "Panongan",
          "Curug",
          "Karawaci",
          "Periuk",
          "Cibodas",
        ],
      },
      {
        name: "Kota Tangerang",
        districts: [
          "Tangerang",
          "Batuceper",
          "Benda",
          "Cipondoh",
          "Jatiuwung",
          "Karawaci",
          "Periuk",
          "Cibodas",
        ],
      },
    ],
  },
  {
    name: "Bali",
    regencies: [
      {
        name: "Kab. Badung",
        districts: ["Kuta", "Kuta Utara", "Mengwi", "Abiansemal", "Petang"],
      },
      {
        name: "Kota Denpasar",
        districts: ["Denpasar Selatan", "Denpasar Barat", "Denpasar Utara", "Denpasar Timur"],
      },
    ],
  },
];
