import { InvoiceRow } from "./types";

export const MOCK_INVOICES: InvoiceRow[] = [
  {
    id: "inv-001",
    date: "2026-05-22",
    ref: "#PO-0982",
    supplierName: "Agen Ayam Subur",
    category: "Bahan Baku Protein (Daging Ayam)",
    nominal: 5250000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-002",
    date: "2026-05-21",
    ref: "#PO-0981",
    supplierName: "Toko Sayur Arief",
    category: "Bahan Baku Sayur & Buah",
    nominal: 2100000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-003",
    date: "2026-05-20",
    ref: "#MANUAL-01",
    category: "Operasional: Isi Ulang Gas LPG 12kg (2 tabung)",
    nominal: 450000,
    statusBukti: "Nota_Gas.jpg",
    fileUrl: "#",
    isManual: true,
  },
  {
    id: "inv-004",
    date: "2026-05-20",
    ref: "#PO-0980",
    supplierName: "UD. Sumber Rejeki",
    category: "Bahan Baku Karbohidat (Beras Premium)",
    nominal: 3600000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-005",
    date: "2026-05-19",
    ref: "#PO-0979",
    supplierName: "CV. Tani Makmur",
    category: "Bahan Baku Sayur & Buah",
    nominal: 1800000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-006",
    date: "2026-05-18",
    ref: "#PO-0978",
    supplierName: "UD. Sumber Rejeki",
    category: "Bahan Baku Karbohidat (Beras Premium)",
    nominal: 3200000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-007",
    date: "2026-05-17",
    ref: "#PO-0977",
    supplierName: "Agen Ayam Subur",
    category: "Bahan Baku Protein (Daging Ayam)",
    nominal: 4800000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-008",
    date: "2026-05-16",
    ref: "#PO-0976",
    supplierName: "UD. Berkah Jaya",
    category: "Bahan Baku Protein (Telur Ayam)",
    nominal: 2800000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-009",
    date: "2026-05-15",
    ref: "#PO-0975",
    supplierName: "Toko Sayur Arief",
    category: "Bahan Baku Sayur & Buah",
    nominal: 1500000,
    statusBukti: "Terekam Sistem",
    isManual: false,
  },
  {
    id: "inv-010",
    date: "2026-05-15",
    ref: "#MANUAL-02",
    category: "Operasional: Air Mineral Galon (10 galon)",
    nominal: 75000,
    statusBukti: "Terekam Sistem",
    isManual: true,
  },
];
