import { MarketSupplierItem } from "./types";

export const MOCK_MARKET_ITEMS: MarketSupplierItem[] = [
  {
    id: "mi-001",
    supplierId: "sup-001",
    supplierName: "UD. Sumber Rejeki",
    itemName: "Beras Premium",
    unit: "kg",
    price: 12000,
    isAnomaly: false,
    latitude: -6.5569,
    longitude: 107.4448,
    mou: true,
  },
  {
    id: "mi-002",
    supplierId: "sup-002",
    supplierName: "CV. Tani Makmur",
    itemName: "Beras Premium",
    unit: "kg",
    price: 11500,
    isAnomaly: false,
    latitude: -6.5612,
    longitude: 107.4501,
    mou: false,
  },
  {
    id: "mi-003",
    supplierId: "sup-003",
    supplierName: "UD. Berkah Jaya",
    itemName: "Beras Premium",
    unit: "kg",
    price: 13000,
    isAnomaly: true,
    latitude: -6.549,
    longitude: 107.438,
    mou: false,
  },
  {
    id: "mi-004",
    supplierId: "sup-004",
    supplierName: "PT. Pangan Sejahtera",
    itemName: "Beras Premium",
    unit: "kg",
    price: 12500,
    isAnomaly: false,
    latitude: -6.5701,
    longitude: 107.4622,
    mou: true,
  },
  {
    id: "mi-005",
    supplierId: "sup-005",
    supplierName: "UD. Sumber Rejeki",
    itemName: "Ayam Broiler",
    unit: "kg",
    price: 32000,
    isAnomaly: false,
    latitude: -6.5569,
    longitude: 107.4448,
    mou: true,
  },
  {
    id: "mi-006",
    supplierId: "sup-002",
    supplierName: "CV. Tani Makmur",
    itemName: "Ayam Broiler",
    unit: "kg",
    price: 31000,
    isAnomaly: false,
    latitude: -6.5612,
    longitude: 107.4501,
    mou: false,
  },
  {
    id: "mi-007",
    supplierId: "sup-006",
    supplierName: "UD. Sayur Segar",
    itemName: "Sayur Bayam",
    unit: "kg",
    price: 8000,
    isAnomaly: false,
    latitude: -6.5488,
    longitude: 107.4312,
    mou: false,
  },
  {
    id: "mi-008",
    supplierId: "sup-003",
    supplierName: "UD. Berkah Jaya",
    itemName: "Telur Ayam",
    unit: "kg",
    price: 28000,
    isAnomaly: false,
    latitude: -6.549,
    longitude: 107.438,
    mou: false,
  },
  {
    id: "mi-009",
    supplierId: "sup-001",
    supplierName: "UD. Sumber Rejeki",
    itemName: "Minyak Goreng",
    unit: "liter",
    price: 17000,
    isAnomaly: false,
    latitude: -6.5569,
    longitude: 107.4448,
    mou: true,
  },
  {
    id: "mi-010",
    supplierId: "sup-004",
    supplierName: "PT. Pangan Sejahtera",
    itemName: "Minyak Goreng",
    unit: "liter",
    price: 16500,
    isAnomaly: false,
    latitude: -6.5701,
    longitude: 107.4622,
    mou: true,
  },
  {
    id: "mi-011",
    supplierId: "sup-007",
    supplierName: "UD. Ikan Segar Laut",
    itemName: "Ikan Tongkol",
    unit: "kg",
    price: 45000,
    isAnomaly: false,
    latitude: -6.562,
    longitude: 107.455,
    mou: false,
  },
  {
    id: "mi-012",
    supplierId: "sup-005",
    supplierName: "UD. Sumber Rejeki",
    itemName: "Tahu Putih",
    unit: "pcs",
    price: 2500,
    isAnomaly: false,
    latitude: -6.5569,
    longitude: 107.4448,
    mou: true,
  },
  {
    id: "mi-013",
    supplierId: "sup-002",
    supplierName: "CV. Tani Makmur",
    itemName: "Tempe",
    unit: "pcs",
    price: 3000,
    isAnomaly: false,
    latitude: -6.5612,
    longitude: 107.4501,
    mou: false,
  },
  {
    id: "mi-014",
    supplierId: "sup-008",
    supplierName: "UD. Sembako Murah",
    itemName: "Gula Pasir",
    unit: "kg",
    price: 15000,
    isAnomaly: true,
    latitude: -6.545,
    longitude: 107.43,
    mou: false,
  },
  {
    id: "mi-015",
    supplierId: "sup-001",
    supplierName: "UD. Sumber Rejeki",
    itemName: "Gula Pasir",
    unit: "kg",
    price: 13500,
    isAnomaly: false,
    latitude: -6.5569,
    longitude: 107.4448,
    mou: true,
  },
];

export const MOCK_ITEM_NAMES = [
  "Beras Premium",
  "Ayam Broiler",
  "Sayur Bayam",
  "Telur Ayam",
  "Minyak Goreng",
  "Ikan Tongkol",
  "Tahu Putih",
  "Tempe",
  "Gula Pasir",
];
